MLFLOW_TRACKING_URI = "https://dagshub.com/Khasim0210/student-risk-classification.mlflow"
MLFLOW_TRACKING_USERNAME = "Khasim0210"
MLFLOW_TRACKING_PASSWORD = "d9c88a089e9e49f5af138c2dbdd9c7f36edfc491"
